import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — Menopause Movement',
  description: 'How Menopause Movement collects, uses, and protects your information.',
}

const LAST_UPDATED = 'May 25, 2026'

export default function PrivacyPage() {
  return (
    <div style={{ backgroundColor: '#f5f3ef', minHeight: '100vh' }}>
      {/* Nav */}
      <header style={{ borderBottom: '1px solid #d9d5ce', backgroundColor: '#f5f3ef' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', padding: '20px 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ fontFamily: 'var(--font-serif), Georgia, serif', fontSize: 18, color: '#1a1a1a', textDecoration: 'none', fontWeight: 400 }}>
            Menopause Movement
          </Link>
          <Link href="/" style={{ fontSize: 13, color: '#6b6b6b', textDecoration: 'none' }}>
            ← Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 760, margin: '0 auto', padding: '64px 32px 96px' }}>
        <p style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#6b6b6b', marginBottom: 16 }}>
          Legal
        </p>
        <h1 style={{ fontFamily: 'var(--font-serif), Georgia, serif', fontSize: 'clamp(32px, 4vw, 48px)', fontWeight: 400, color: '#1a1a1a', lineHeight: 1.15, letterSpacing: '-0.02em', marginBottom: 12 }}>
          Privacy Policy
        </h1>
        <p style={{ fontSize: 14, color: '#6b6b6b', marginBottom: 56 }}>
          Last updated: {LAST_UPDATED}
        </p>

        <div style={{ fontSize: 16, color: '#1a1a1a', lineHeight: 1.8 }}>

          <Section title="1. Overview">
            <p>Menopause Movement ("we", "us", or "our") operates the website at menopausemovement.com. This Privacy Policy explains what information we collect when you use our quiz and results tool, how we use it, and your rights regarding that information.</p>
            <p>By using this site, you agree to the practices described in this policy.</p>
          </Section>

          <Section title="2. Information We Collect">
            <Subsection title="Quiz answers">
              <p>When you take our quiz, you voluntarily provide information including your age range, menopause stage, exercise habits, health symptoms, stress levels, sleep quality, dietary pattern, and medical conditions. This information is stored temporarily in your browser's session storage and is used solely to generate your personalized plan. It is not transmitted to or stored on our servers beyond what is necessary to process your request.</p>
            </Subsection>
            <Subsection title="Email address">
              <p>We offer an optional email capture to unlock your full results. If you choose to provide your email address, we store it to send you relevant fitness and wellness content related to menopause. You can unsubscribe at any time by clicking the unsubscribe link in any email we send.</p>
            </Subsection>
            <Subsection title="Usage data">
              <p>We may collect standard web analytics data such as pages visited, time spent on the site, device type, and browser type. This data is aggregated and anonymized and cannot be used to identify you personally.</p>
            </Subsection>
          </Section>

          <Section title="3. How We Use Your Information">
            <p>We use the information we collect to:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8, marginBottom: 8 }}>
              <li style={{ marginBottom: 8 }}>Generate your personalized menopause fitness plan using AI</li>
              <li style={{ marginBottom: 8 }}>Send you educational content about menopause fitness and wellness (if you opt in with your email)</li>
              <li style={{ marginBottom: 8 }}>Improve and maintain the quality of the quiz and recommendations</li>
              <li style={{ marginBottom: 8 }}>Understand how the site is being used in aggregate</li>
            </ul>
            <p>We do not sell, rent, or share your personal information with third parties for their marketing purposes.</p>
          </Section>

          <Section title="4. AI-Generated Content">
            <p>Your quiz answers are sent to Anthropic's API to generate your personalized fitness plan. Anthropic processes this data to return your results. Anthropic's use of this data is governed by their own privacy policy and API terms of service. We do not store your quiz answers on our servers after your plan has been generated.</p>
            <p>The fitness recommendations provided are generated by an AI model and are for informational and educational purposes only. See Section 8 (Medical Disclaimer) for important limitations.</p>
          </Section>

          <Section title="5. Cookies and Local Storage">
            <p>We use your browser's <strong>session storage</strong> to temporarily hold your quiz answers during your session. This data is automatically cleared when you close your browser tab.</p>
            <p>We use your browser's <strong>local storage</strong> to remember whether you have already provided your email address, so we do not ask again on subsequent visits.</p>
            <p>We do not use tracking cookies for advertising purposes.</p>
          </Section>

          <Section title="6. Data Retention">
            <p>Quiz answers are held in your browser's session storage only and are never stored on our servers beyond the duration of your API request.</p>
            <p>If you provide your email address, we retain it until you unsubscribe or request deletion.</p>
            <p>Usage analytics data is retained in anonymized, aggregated form.</p>
          </Section>

          <Section title="7. Your Rights">
            <p>You have the right to:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8, marginBottom: 8 }}>
              <li style={{ marginBottom: 8 }}>Request deletion of your email address from our records at any time</li>
              <li style={{ marginBottom: 8 }}>Opt out of email communications by clicking "Unsubscribe" in any email</li>
              <li style={{ marginBottom: 8 }}>Request information about what personal data we hold about you</li>
            </ul>
            <p>To exercise any of these rights, contact us at the email address listed in Section 10.</p>
          </Section>

          <Section title="8. Medical Disclaimer">
            <p><strong>The content provided by Menopause Movement is for informational and educational purposes only. It is not medical advice, and it does not create a doctor-patient relationship.</strong></p>
            <p>The AI-generated fitness recommendations are based on general research about menopause and exercise. They are not a substitute for personalized advice from a qualified healthcare provider. Always consult your doctor or a licensed healthcare professional before starting a new exercise program, especially if you have existing medical conditions, are pregnant, or have recently had surgery or injury.</p>
            <p>We are not responsible for any health outcomes arising from your use of or reliance on the content generated by this tool.</p>
          </Section>

          <Section title="9. Children's Privacy">
            <p>This site is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.</p>
          </Section>

          <Section title="10. Contact Us">
            <p>If you have questions about this Privacy Policy or want to exercise your rights, please contact us at:</p>
            <p style={{ marginTop: 12 }}>
              <strong>Menopause Movement</strong><br />
              Email: <a href="mailto:hello@menopausemovement.com" style={{ color: '#1a1a1a' }}>hello@menopausemovement.com</a>
            </p>
          </Section>

          <Section title="11. Changes to This Policy">
            <p>We may update this Privacy Policy from time to time. When we do, we will update the "Last updated" date at the top of this page. Continued use of the site after changes are posted constitutes your acceptance of the updated policy.</p>
          </Section>

        </div>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid #d9d5ce', padding: '32px', textAlign: 'center' }}>
        <p style={{ fontSize: 13, color: '#6b6b6b' }}>
          © {new Date().getFullYear()} Menopause Movement ·{' '}
          <Link href="/privacy" style={{ color: '#6b6b6b', textDecoration: 'underline', textUnderlineOffset: '3px' }}>
            Privacy Policy
          </Link>
        </p>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 48 }}>
      <h2 style={{
        fontFamily: 'var(--font-serif), Georgia, serif',
        fontSize: 22,
        fontWeight: 400,
        color: '#1a1a1a',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottom: '1px solid #d9d5ce',
      }}>
        {title}
      </h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {children}
      </div>
    </div>
  )
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 style={{ fontSize: 15, fontWeight: 600, color: '#1a1a1a', marginBottom: 8 }}>
        {title}
      </h3>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {children}
      </div>
    </div>
  )
}
